input_features:
  - name: image_path
    type: image
    preprocessing:
      height: 96
      width: 96
      num_channels: 3
      missing_value_strategy: fill_with_const
      fill_value: 0
    encoder:
      type: stacked_cnn
      conv_layers:
        # Block 1
        - num_filters: 32
          filter_size: 3
          padding: same
          activation: relu
          norm: batch
        - pool_size: 3
          pool_type: max
        - dropout: 0.25
        # Block 2
        - num_filters: 64
          filter_size: 3
          padding: same
          activation: relu
        - num_filters: 64
          filter_size: 3
          padding: same
          activation: relu
          norm: batch
        - pool_size: 2
          pool_type: max
        - dropout: 0.25
        # Block 3
        - num_filters: 128
          filter_size: 3
          padding: same
          activation: relu
          norm: batch
        - num_filters: 128
          filter_size: 3
          padding: same
          activation: relu
          norm: batch
        - pool_size: 2
          pool_type: max
        - dropout: 0.25
      fc_layers:
        - output_size: 1024
          activation: relu
          norm: batch
          dropout: 0.5

output_features:
  - name: label
    type: category
    decoder:
      type: classifier
    loss:
      type: softmax_cross_entropy

trainer:
  optimizer:
    type: adam
  learning_rate: 0.001
  epochs: 150
  batch_size: 32
  early_stop: 10

preprocessing:
  split:
    type: fixed
    column: split
