input_features:
  - name: image_path
    type: image
    preprocessing:
      height: 96
      width: 96
      num_channels: 3
    encoder:
      type: stacked_cnn
      conv_layers:
        - num_filters: 32
          filter_size: 3
          padding: same
          activation: relu
          norm: batch
        - pool_size: 3
          pool_type: max
        - dropout: 0.25

        - num_filters: 64
          filter_size: 3
          padding: same
          activation: relu
        - num_filters: 64
          filter_size: 3
          padding: same
          activation: relu
          norm: batch
        - pool_size: 2
          pool_type: max
        - dropout: 0.25

        - num_filters: 128
          filter_size: 3
          padding: same
          activation: relu
          norm: batch
        - num_filters: 128
          filter_size: 3
          padding: same
          activation: relu
          norm: batch
        - pool_size: 2
          pool_type: max
        - dropout: 0.25

      fc_layers:
        - output_size: 1024
          activation: relu
          norm: batch
          dropout: 0.5

output_features:
  - name: label
    type: category
    loss:
      type: softmax_cross_entropy

trainer:
  epochs: 150
  batch_size: 32
  learning_rate: 0.001
  optimizer:
    type: adam
  early_stop: 10
  eval_batch_size: 32

preprocessing:
  split:
    type: fixed
    column: split
