
input_features:
  - name: color_histogram
    type: numerical
    encoder: dense
  - name: hu_moments
    type: numerical
    encoder: dense
  - name: haralick_texture
    type: numerical
    encoder: dense

output_features:
  - name: label
    type: category
    loss:
      type: softmax_cross_entropy

combiner:
  type: concat
  fc_layers:
    - output_size: 1024
      activation: relu
      dropout: 0.5
  num_layers: 1
  output_size: 1024
  use_bias: true

trainer:
  epochs: 150
  batch_size: 32
  learning_rate: 0.001
  optimizer:
    type: adam
  early_stop: 10
  eval_batch_size: 32

preprocessing:
  split:
    type: fixed
    column: split
